version: '2'
services:
    resource-postgresql:
        image: postgres:11.5
        # volumes:
        #     - ~/volumes/jhipster/resource/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=resource
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
